# Copyright (c) 2023, Toyota Motor Corporation
# Copyright (c) 2023, MID Academic Promotions, Inc.
# All rights reserved.

FROM ros:humble-ros-core-jammy

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND noninteractive

RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt update && \
    apt install -y git python-is-python3 g++ make libgflags-dev \
    python3-colcon-common-extensions \
    python3-numpy \
    python3-opencv \
    python3-psutil \
    libeigen3-dev \
    libpoco-dev \
    libboost-system-dev \
    libboost-filesystem-dev \
    libsdl1.2-dev \
    libsdl-image1.2-dev \
    ros-humble-rclpy \
    ros-humble-rosidl-default-generators \
    ros-humble-tf-transformations \
    ros-humble-tf2 \
    ros-humble-tf2-msgs \
    ros-humble-tf2-geometry-msgs \
    ros-humble-actionlib-msgs \
    ros-humble-geometry-msgs \
    ros-humble-control-msgs \
    ros-humble-trajectory-msgs \
    ros-humble-sensor-msgs \
    ros-humble-nav-msgs \
    ros-humble-vision-msgs \
    ros-humble-gazebo-msgs \
    ros-humble-topic-tools \
    ros-humble-joint-state-publisher \
    ros-humble-moveit \
    ros-humble-moveit-ros-move-group \
    ros-humble-moveit-ros-perception \
    ros-humble-pinocchio \
    ros-humble-nav2-map-server \
    ros-humble-nav2-bringup \
    ros-humble-navigation2 \
    ros-humble-robot-state-publisher \
    ros-humble-depth-image-proc \
    ros-humble-image-transport-plugins \
    ros-humble-image-proc \
    ros-humble-depth-image-proc \
    ros-humble-rviz-imu-plugin \
    ros-humble-rqt-robot-steering \
    ros-humble-rqt-tf-tree \
    ros-humble-controller-interface \
    ros-humble-realtime-tools \
    ros-humble-action-tutorials-interfaces \
    ros-humble-example-interfaces \
    ros-humble-diagnostic-updater \
    ros-humble-std-srvs \
    ros-humble-rmw-cyclonedds-cpp \
    #ros-humble-pcl \
    libode-dev \
    ipython3 \
    python3-stl \
    python3-rosdep

RUN source /opt/ros/$ROS_DISTRO/setup.bash && \
    mkdir -p /ws/src && \
    cd /ws/src && \
        git clone -b humble https://github.com/hsr-project/hsrb_drivers.git && \
        git clone -b humble https://github.com/hsr-project/tmc_drivers.git && \
        git clone -b humble https://github.com/hsr-project/tmc_gazebo.git && \
        git clone -b humble https://github.com/hsr-project/hsrb_simulator.git && \
        git clone -b humble https://github.com/hsr-project/hsrb_controllers.git && \
        git clone -b humble https://github.com/hsr-project/hsrb_control.git && \
        git clone -b humble https://github.com/hsr-project/hsrb_moveit.git && \
        git clone -b humble https://github.com/hsr-project/hsr_common.git && \
        git clone -b humble https://github.com/hsr-project/hsrb_launch.git && \
        git clone -b humble https://github.com/hsr-project/hsrb_interfaces.git && \
        git clone -b rc26 https://github.com/Hibikino-Musashi-Home/hsrb_common.git && \
        git clone -b humble https://github.com/hsr-project/tmc_common.git && \
        git clone -b humble https://github.com/hsr-project/tmc_common_msgs.git && \
        git clone -b humble https://github.com/hsr-project/tmc_realtime_control.git && \
        git clone -b humble https://github.com/hsr-project/hsrb_manipulation.git && \
        git clone -b humble https://github.com/hsr-project/tmc_manipulation.git && \
        git clone -b humble https://github.com/hsr-project/tmc_manipulation_local_planner.git && \
        git clone -b humble https://github.com/hsr-project/tmc_manipulation_base.git && \
        git clone -b humble https://github.com/hsr-project/tmc_manipulation_planner.git && \
        git clone -b humble https://github.com/hsr-project/tmc_voice.git && \
        git clone -b humble https://github.com/hsr-project/hsrb_rosnav.git && \
        git clone -b humble https://github.com/hsr-project/tmc_navigation.git && \
        git clone -b humble https://github.com/hsr-project/tmc_teleop.git && \
        git clone -b humble https://github.com/hsr-project/hsrb_teleop.git && \
        git clone -b humble https://github.com/hsr-project/tmc_database.git && \
        git clone -b humble https://github.com/hsr-project/hsrb_robot_local_planner.git && \
        git clone -b humble https://github.com/hsr-project/hsrb_robot.git && \
        git clone -b main https://github.com/hsr-project/pick_and_place_example.git && \
        git clone -b humble https://github.com/hsr-project/instance_segmentation_msgs.git && \
        git clone -b humble https://github.com/hsr-project/cv_bridge_util.git && \
        git clone -b main https://github.com/hsr-project/coordinate_transform_util_ros.git && \
        git clone -b humble https://github.com/hsr-project/compressed_rgbd_msgs.git && \
        git clone -b humble https://github.com/hsr-project/tmc_point_cloud.git && \
        git clone -b humble https://github.com/hsr-project/graspnet_ros.git && \
        git clone -b humble https://github.com/hsr-project/hsrb_system_inspection.git && \
        git clone -b ignition/humble https://github.com/ry0hei-kobayashi/tmc_wrs_gazebo.git && \
        git clone -b ros2_csm_eigen https://github.com/AlexKaravaev/csm.git && \
        git clone -b main https://github.com/AlexKaravaev/ros2_laser_scan_matcher.git && \

    rm -rf hsrb_launch/hsrb_robot_launch && \
    rm -rf hsrb_gazebo_launch/tmc_grid_map_server && \
    rm -rf hsrb_simulator/hsrb_rviz_simulator && \
    rm -rf tmc_drivers/tmc_pgr_camera && \
    cd .. && \
    . /opt/ros/humble/setup.bash && apt update -y && rosdep init && rosdep update && rosdep install --ignore-src -r -y -i --from-paths src && \
    colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --parallel-workers $(nproc)



#RUN source /opt/ros/$ROS_DISTRO/setup.bash && \
#    mkdir -p /ws/src && \
#    cd /ws/src && \
#    git clone -b humble https://github.com/hsr-project/hsrb_description.git && \
#    git clone -b humble https://github.com/hsr-project/hsrb_meshes.git && \
#    git clone -b humble https://github.com/hsr-project/tmc_common.git && \
#    git clone -b humble https://github.com/hsr-project/hsr_common.git && \
#    git clone -b humble https://github.com/hsr-project/tmc_drivers.git && \
#    git clone -b humble https://github.com/hsr-project/tmc_database.git && \
#    git clone -b humble https://github.com/hsr-project/tmc_manipulation_base.git && \
#    git clone -b humble https://github.com/hsr-project/tmc_manipulation.git && \
#    git clone -b humble https://github.com/hsr-project/tmc_manipulation_planner.git && \
#    git clone -b humble https://github.com/hsr-project/hsrb_manipulation.git && \
#    git clone -b humble https://github.com/hsr-project/hsrb_moveit_plugins.git && \
#    git clone -b humble https://github.com/hsr-project/hsrb_moveit_config.git && \
#    git clone -b humble https://github.com/hsr-project/tmc_common_msgs.git && \
#    git clone -b humble https://github.com/hsr-project/tmc_realtime_control.git && \
#    git clone -b humble https://github.com/hsr-project/tmc_navigation.git && \
#    git clone -b humble https://github.com/hsr-project/hsrb_rosnav.git && \
#    git clone -b humble https://github.com/hsr-project/hsrb_robot.git && \
#    git clone -b ros2_csm_eigen https://github.com/AlexKaravaev/csm.git && \
#    git clone -b main https://github.com/AlexKaravaev/ros2_laser_scan_matcher.git && \
#    git clone -b humble https://github.com/hsr-project/tmc_voice.git && \
#    git clone -b humble https://github.com/hsr-project/hsrb_launch.git && \
#    git clone -b humble https://github.com/hsr-project/hsrb_interfaces.git && \
#    git clone -b feature/ros2 https://github.com/hsr-project/tmc_gazebo_task_evaluators.git && \
#    git clone -b feature/ros2 https://github.com/hsr-project/tmc_wrs_gazebo.git && \
#    rm -rf tmc_drivers/tmc_pgr_camera && \
#    rm -rf tmc_voice/tmc_talk_hoya_py && \
#    cd .. && \
#    colcon build

# RUN curl -sSL https://raw.githubusercontent.com/NVIDIA-Omniverse/IsaacSim-ros_workspaces/main/humble_ws/fastdds.xml -o /fastdds.xml
# ENV FASTRTPS_DEFAULT_PROFILES_FILE /fastdds.xml
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

RUN curl -sSL https://github.com/hsr-project/hsrb_rosnav/raw/refs/heads/master/hsrb_rosnav_config/maps/white_space/map.yaml -o /map.yaml
RUN curl -sSL https://github.com/hsr-project/hsrb_rosnav/raw/refs/heads/master/hsrb_rosnav_config/maps/white_space/white_space.pgm -o /white_space.pgm

ADD launch/hsr.launch.py /hsr.launch.py
ADD launch/teleop.launch.py /teleop.launch.py
ADD launch/hsrb_relay_topics.launch.xml /hsrb_relay_topics.launch.xml
ADD launch/hsrb_sensor_frames.launch.xml /hsrb_sensor_frames.launch.xml
ADD scripts/rgbd_republisher.py /rgbd_republisher.py
ADD scripts/reset_world_matcher_helper.py /reset_world_matcher_helper.py
ADD assets/carrobo-isaac.rviz /carrobo-isaac.rviz

COPY assets/cyclonedds.xml /cyclonedds.xml
ADD assets/ros_entrypoint.sh.ros2 /ros_entrypoint.sh

CMD [ "ros2", "launch", "/hsr.launch.py" ]
#CMD [ "tail", "-f", "/dev/null" ]
